/*
 * Dreamlines Bookings Api
 *
 * This is prototype of the Dreamlines Bookings API The api allows access the bookings and their related SalesUnits. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Dreamlines.Presentation.Api.Attributes;
using Dreamlines.Presentation.Api.Models;
using Dreamlines.ApplicationServices;
using System.Linq;
using IO.Swagger.Models;

namespace Dreamlines.Presentation.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BookingApiController : ControllerBase
    {
		private readonly IBookingService bookingService;

		public BookingApiController(IBookingService bookingService)
		{
			this.bookingService = bookingService;
		}

        /// <summary>
        /// Returns all the bookings that belong to a salesunit with the given ID
        /// </summary>
        /// <param name="salesUnitId">ID of the salesUnit</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid salesunit id</response>
        [HttpGet]
        [Route("/DreamlinesApi/1.0.0/booking/findBySalesUnitId/{salesUnitId}")]
        [ValidateModelState]
        [SwaggerOperation("FindBySalesUnitId")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Booking>), description: "successful operation")]
        public virtual IActionResult FindBySalesUnitId([FromRoute][Required] int salesUnitId)
        {
            var bookings = bookingService.ListBySalesUnitId(salesUnitId);
            return StatusCode(200, bookings.Select(booking => new BookingSummary(booking)));
        }
        
    }
}
